### PR TITLE
Add image and name properties to Channel and User objects

### LINKED ISSUE #3035: Add name and image properties
### Acceptance criteria

To accept this task we need to complete the following items:

- [ ] `Channel` and `User` object have `image` and `name` properties
- [ ] Existing "virtual" properties are removed

### PR DESCRIPTION
**Pull request by adasiewiczr**
closes #3035 

### 🎯 Goal

Add image and name properties to `Channel` and `User` objects.

### 🛠 Implementation details

1. Converted virtual properties to properties
2. Added sending new properties when connecting the user
3. Updated tests

### 🧪 Testing

Smoke test the sample apps. Make sure both `name` and `image` are being displayed properly

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes
- [x] New code is covered by unit tests
- [ ] ~Comparison screenshots added for visual changes~
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### CODE REVIEW

**Review by skydoves — COMMENTED** [review]
Totally looks great to me!
You might want to update the following docusaurus as well:

- `01-user.mdx`
- `03-getting-started.mdx`

### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [x] Compose sample runs & works
- [x] New feature tested and works
- [x] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

**Comment by adasiewiczr** [comment]
great catch @skydoves. Thanks!

**Review by skydoves — APPROVED** [review]
Looks good!

### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [x] Compose sample runs & works
- [x] New feature tested and works
- [x] Release notes and docs clearly describe changes
- [x] All code we touched has new or updated KDocs

**Review by amitkma — APPROVED** [review]
Works as expected.

### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [x] Compose sample runs & works
- [x] New feature tested and works
- [x] Release notes and docs clearly describe changes
- [x] All code we touched has new or updated KDocs

**Review by MarinTolic — APPROVED** [review]
### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [x] Compose sample runs & works
- [x] UI Changes correct (before & after images)
- [x] Bugs validated (bugfixes)
- [x] New feature tested and works
- [x] Release notes and docs clearly describe changes
- [x] All code we touched has new or updated KDocs

**Pull request merged**
