### PR TITLE
Add padding to the navbar that add some space between icon badge and the top border

### PR DESCRIPTION
**Pull request by JcMinarro**
### Description

Add padding to the navbar that add some space between icon badge and the top border

| Before | After |
| --- | --- |
| photo_2021-01-21_12-52-12  |  photo_2021-01-21_12-52-13 |

### Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- ~[ ] Changelog updated with client-facing changes
- ~[ ] New code is covered by unit tests
- [x] Comparison screenshots added for visual changes
- [x] Reviewers added

### CODE REVIEW

**Review by adasiewiczr — APPROVED** [review]

**Comment by bychkovdmitry** [comment]
Checking why this logic stopped working

```
fun BottomNavigationView.setBadgeNumber(@IdRes menuItemId: Int, badgeNumber: Int) {
    val badge = getBadge(menuItemId)
        ?: getOrCreateBadge(menuItemId).apply {
            horizontalOffset = -context.getDimensionPixelSize(R.dimen.badge_horizontal_offset)
            verticalOffset = context.getDimensionPixelSize(R.dimen.badge_vertical_offset)
            backgroundColor = context.getColorFromRes(R.color.bottom_nav_badge_color)
        }
    badge.isVisible = badgeNumber > 0
    badge.number = badgeNumber
}
```

**Comment by bychkovdmitry** [comment]
Don't know what happened, maybe we updated the design library and badges are allocated when the view is created. Here is the fix:
https://github.com/GetStream/stream-chat-android/pull/1256

**Review by bychkovdmitry — CHANGES_REQUESTED** [review]
Sorry, my logic stopped working not long ago, here is the fix with comparison screenshots between our designs and our app:
https://github.com/GetStream/stream-chat-android/pull/1256

**Comment by zsmb13** [comment]
This is fixed by the PR linked above, dropping this one

**Pull request closed without merging**
