### PR TITLE
Configure Spotless license header for Kotlin and Java files

### PR DESCRIPTION
**Pull request by skydoves**
### 🎯 Goal

Configure Spotless license header for Kotlin and Java files. (#3012)

The license header will be added automatically on the top of the new `.kt` and `.java` files by running 
the `./gradlew spotlessApply` commad, which is already included in our [git hook](https://github.com/GetStream/stream-chat-android/blob/main/hooks/pre-commit#L9).

- [15f5285](https://github.com/GetStream/stream-chat-android/pull/3290/commits/15f5285b5bbbfcbe9c427eadc87ea6efe25201a0): Configured Spotless Gradle.
- [a51b2ad](https://github.com/GetStream/stream-chat-android/pull/3290/commits/a51b2ad4241a38e8525b1578938db5dd4671d907): [Warning - Your Web browser might be lagged 😅] Added the License header and apply Spotless.
- [082bf64](https://github.com/GetStream/stream-chat-android/pull/3290/commits/082bf643fb3fbe8c2094fc4f77a906273f1eaa16): Added License to the README file.

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [x] Changelog is updated with client-facing changes

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF
gif

### CODE REVIEW

**Review by filbabic — APPROVED** [review]
The header looks good to me, will this make sure all new files have the header too?

**Comment by skydoves** [comment]
> The header looks good to me, will this make sure all new files have the header too?

@filbabic Yes, the license header will be added automatically on all new files by running `./gradlew spotlessApply` command and the command will be run by the [git hook](https://github.com/GetStream/stream-chat-android/blob/main/hooks/pre-commit#L9).

**Comment by JcMinarro** [comment]
> > The header looks good to me, will this make sure all new files have the header too?
> 
> @filbabic Yes, the license header will be added automatically on all new files by running `./gradlew spotlessApply` command and the command will be run by the [git hook](https://github.com/GetStream/stream-chat-android/blob/main/hooks/pre-commit#L9).

And our Github-Actions will fail in case it is not present, right?

**Comment by skydoves** [comment]
> And our Github-Actions will fail in case it is not present, right?

@JcMinarro Yes,  Github-Actions will faill if the license is not present.

**Review by JcMinarro — APPROVED** [review]

**Pull request merged**
