### PR TITLE
Task/2910 add loading more indicator pinned messages

### LINKED ISSUE #2910: Add loading more indicator to PinnedMessageListView

### PR DESCRIPTION
**Pull request by filbabic**
### 🎯 Goal

Fixes #2910 also improves the implementation of scroll listeners.

### 🛠 Implementation details

Added an empty message which signals that the list should show a loading more spinner at the end.

Added a separate endless scroll handler for MessageList since it's not using reverseLayout but it warrants scroll to the top (instead of bottom). Fixed implementation for scrolling in other places where the previous endless listener was used:

image

### 🎨 UI Changes

_Add relevant screenshots_

| Before | After |
| --- | --- |
| img | img |

### 🧪 Testing

Go through various parts of our UI in the XML sample and trigger pagination where available. Things should work as you'd expect based on their ordering (layout manager) and the scroll.

#### General
- [x] Assigned a person / code owner group (required)
- [x] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [ ] Changelog is updated with client-facing changes
- [ ] Comparison screenshots added for visual changes
- [x] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### CODE REVIEW

**Review by bychkovdmitry — CHANGES_REQUESTED** [review]
Doesn't work due to the following:

```
_state.value = currentState.copy(
    isLoading = true,
    results = currentState.results + Message()
)

state.observe(lifecycleOwner) { state ->
        when {
            state.isLoading -> {
                // Loading more arrives here
                view.showLoading()
            }
            else -> {
               // I suppose loading more should take this branch as we want to render loading more item (a message with empty ID)
                view.showMessages(state.results)
            }
      }
}
```

**Comment by bychkovdmitry** [comment]
### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [x] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

**Review by bychkovdmitry — APPROVED** [review]
Works well! Do we need to update the change log?

**Review by adasiewiczr — APPROVED** [review]
Let's update the CHANGELOG but looks good besides that!

### ☑️Reviewer Checklist
- [x] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [x] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

**Comment by filbabic** [comment]
Updated changelog!

**Pull request merged**
