### PR TITLE
Fix MessageListItemDiffCallback

### PR DESCRIPTION
**Pull request by JcMinarro**
Fix MessageListItemDiffCallback

### CODE REVIEW

**Review by zsmb13 — COMMENTED** [review]
I can't comment on that line, but are we content (no pun intended) with how the `areContentsTheSame` method works? Is that a valid way to compare the instances, by their `equals` method? I know there were some concerns around this.

**Comment by JcMinarro** [comment]
> I can't comment on that line, but are we content (no pun intended) with how the `areContentsTheSame` method works? Is that a valid way to compare the instances, by their `equals` method? I know there were some concerns around this.

For now we can continue with this implementation, it is not the best and we will need to find other solution.
The wrong case with this solution is that a message is rendered on every change, despite of the change is important for the UI or not

**Comment by tschellenbach** [comment]
I don't think there are any message changes that change the message but don't result in a UI update. Can't think of any at least.

**Comment by JcMinarro** [comment]
> I don't think there are any message changes that change the message but don't result in a UI update. Can't think of any at least.

Some example could be `MessageListItem.MessageItem.Message.User::online`
This flag notify us if a user is online or not, but it is not shown on the MessageListView. 
If it is updated, the message will be rendered again, without any change for the user that is reading the chat

**Review by zsmb13 — APPROVED** [review]
This is an obvious improvement for now, and we can get back to the content comparison at a later time.

**Pull request merged**
