### PR TITLE
[CAS-815] Document TransformStyle class

### PR DESCRIPTION
**Pull request by bychkovdmitry**
https://stream-io.atlassian.net/browse/CAS-815

### 🎯 Goal

Add docs for `TransformStyle` class

### 🛠 Implementation details

- [Docs](https://getstream.io/chat/docs/android/global_customization/?language=kotlin)
- [Cookbook](https://github.com/GetStream/stream-chat-android/wiki/UI-Cookbook#global-customization)

### ☑️ Checklist

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [X] PR targets the `develop` branch
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [X] Affected documentation updated (CMS, cookbooks, tutorial)
- [X] Reviewers added

### CODE REVIEW

**Comment by leandroBorgesFerreira** [comment]
Don't we need a Java examaple here? https://getstream.io/chat/docs/android/global_customization/?language=kotlin

**Comment by bychkovdmitry** [comment]
> Don't we need a Java example here? https://getstream.io/chat/docs/android/global_customization/?language=kotlin

Just don't look that great in java :)

**Comment by bychkovdmitry** [comment]
Done

**Review by leandroBorgesFerreira — APPROVED** [review]
🐑 🐑 🐑

**Pull request merged**
