### PR TITLE
Event thread looper

### PR DESCRIPTION
**Pull request by jeffdgr8**
# Submit a pull request

## CLA

- [X] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [X] The code changes follow best practices
- [X] Code changes are tested (add some information if not applicable)

## Description of the pull request
Run health check and monitor routines on background event thread, instead of UI thread.

Fixes https://github.com/GetStream/stream-chat-android/issues/418

### CODE REVIEW

**Comment by tschellenbach** [comment]
Sorry for the slow reply. We're currently working on splitting out our low-level client. WIP is here: https://github.com/getstream/stream-chat-android-client

Related: https://github.com/GetStream/stream-chat-android-client/blob/master/library/src/main/java/io/getstream/chat/android/client/socket/HealthMonitor.kt#L12

@elevenetc this pull request looks good in my opinion, what do you think?

Few questions while you're here:

* Are you using the custom views or working with the lowlevel client or livedata directly?
* Are you using RXJava or Livedata/databinding for your app?

**Comment by jeffdgr8** [comment]
@tschellenbach thanks for following up. We are using LiveData and data binding in our app. We have some RxJava, but new code utilizes Kotlin Coroutines wherever possible. @Chikrix can add additional context. I know one view customization that we've needed is the ability to show a conversation as selected for displaying the conversation list and conversation detail on the screen at the same time on larger displays.

**Comment by elevenetc** [comment]
@jeffdgr8 Thread `EventHandlerThread` is indeed useless currently. It just finishes and `EventHandler` is used as it is. 
Wrapping handler into thread fixes the issue, the only problem `Looper.loop()` never stops.
```
Looper.prepare();
mHandler = new EventHandler(webSocketService);
Looper.loop();
```
And we're not reusing `StreamWebSocketService`. So `EventHandlerThread` runs forever and keeps reference to instance of `StreamWebSocketService`. And SDK currently creates new instance of `StreamWebSocketService` when app goes into foreground and when socket is reconnected. Looper should be stopped.

**Comment by jeffdgr8** [comment]
@elevenetc with your understanding of how this should be working, can you suggest edits such that it works as expected on a background thread?

`mMonitor` and `mHealthCheck` both reschedule themselves to be run again after an interval of 1 or 30 seconds. As I described in https://github.com/GetStream/stream-chat-android/issues/418, the current behavior is actually that `mHealthCheck` is getting called twice every 30 seconds, 1 second apart and on the main UI thread. So is this then happening even more often as `StreamWebSocketService` is recreated and schedules additional `mHealthCheck` routines?

**Comment by elevenetc** [comment]
Health monitor should send ping message every N seconds while socket is connected, and try to reconnect when ping is not returned in a certain amount of time.
Current implementation is quite messy and eventually requires refactoring and it is done partly in the next version (`4.x.x`) of SDK which Thierry mentioned. We're still planning to support `3.x.x`, so I don't think it would be easy to avoid recreation of `StreamWebSocketService`, but monitor could be extracted from `StreamWebSocketService` as another service/thread which is:
1. created when `StreamWebSocketService.connect` is called
2. started when socket is connected
2.5 calls reconnection if ping is not returned
3. paused when socket is disconnected
4. destroyed when `StreamWebSocketService.disconnect` is called

**Comment by tschellenbach** [comment]
closing this since the client has been moved to:
https://github.com/GetStream/stream-chat-android-client

**Pull request closed without merging**
