### PR TITLE
[ISSUE-3899] update dependencies

### PR DESCRIPTION
**Pull request by leandroBorgesFerreira**
### 🎯 Goal

Update dependencies and compile de SDK

### 🛠 Implementation details

Bumping dependencies
Applying formation of spotless. 
Updating detekt baseline

#### General
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] Assigned a person / code owner group (required)
- [ ] Thread with the PR link started in a respective Slack channel (#android-chat-core or #android-chat-ui) (required)
- [x] PR targets the `develop` branch
- [x] PR is linked to the GitHub issue it resolves

#### Code & documentation
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (KDocs, docusaurus, tutorial)

### ☑️Reviewer Checklist
- [ ] UI Components sample runs & works
- [ ] Compose sample runs & works
- [ ] UI Changes correct (before & after images)
- [ ] Bugs validated (bugfixes)
- [ ] New feature tested and works
- [ ] Release notes and docs clearly describe changes
- [ ] All code we touched has new or updated KDocs

### 🎉 GIF

_Please provide a suitable gif that describes your work on this pull request_

### CODE REVIEW

**Comment by leandroBorgesFerreira** [comment]
Hello @workspace. I'm sorry that I did not see it in my last review, but you also need to add offline support to your PR. You also need to save those messages in the database in a way that the SDK can fetch them to show the thread messages if they were already loaded. 
Check your changes in offline support: 

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/10619102/182404949-941abe64-4137-44ac-9522-f94f75729230.mov" controls="controls" muted="muted" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/10619102/182404911-7a1e2d96-1fa5-426d-a78c-5ba7acfd9572.mov" controls="controls" muted="muted" />
</td>
</tr>
</tbody>

**Review by adasiewiczr — APPROVED** [review]
As discussed - let's update the CHANGELOG and good to merge!

**Review by skydoves — APPROVED** [review]
Looks good to me!

**Review by kanat — APPROVED** [review]
LGTM

**Comment by adasiewiczr** [comment]
@leandroBorgesFerreira can you resolve the conflict and merge?

**Pull request merged**
