### PR TITLE
Fix publishing of jar artifacts

### PR DESCRIPTION
**Pull request by Miha-x64**
The original publishing script gave me good pom.xml for aar artifacts, but jar ones had no `<dependencies>` blocks. So here's a fix borrowed from Gradle docs.

### CODE REVIEW

**Review by zsmb13 — APPROVED** [review]
LGTM, but let's get a second review too, @JcMinarro

**Comment by Miha-x64** [comment]
Oops, I'm sorry for misspelled 'of' in the commit message. Unfortunately, the change is done though GitHub interface and I can't reword the commit without checking out the whole project.

**Review by JcMinarro — APPROVED** [review]
Thanks for the PR

**Comment by Miha-x64** [comment]
Thanks! Consider also updating [the article](https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/) and [the gist](https://gist.github.com/zsmb13/56ed98c8fe916de441f2a9d8e060cd4a#file-publish-module-gradle-L38).

**Comment by zsmb13** [comment]
@Miha-x64 Already have that on my TODO list, will update the article in all the different places where it's published as well 😄  Thanks for the catch again.

**Pull request merged**
