### PR TITLE
[WIP] Update/custom text font

### PR DESCRIPTION
**Pull request by adrian09h**
# Submit a pull request

## ChannelListView
```xml
<com.getstream.sdk.chat.view.ChannelListView
	...
	app:streamChannelTitleTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamLastMessageTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamLastMessageDateTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamReadStateTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamAvatarTextFontPath="fonts/LilyoftheValley.ttf"
	...
/>
```

image

## ChannelHeaderView
```xml
<com.getstream.sdk.chat.view.ChannelHeaderView
	...      
	app:streamChannelHeaderTitleTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamAvatarTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamChannelHeaderLastActiveTextFontPath="fonts/LilyoftheValley.ttf"
	...
/>
```

image

## MessageListView
```xml
<com.getstream.sdk.chat.view.MessageListView
	...
	app:streamMessageTextFontPathMine="fonts/LilyoftheValley.ttf"
	app:streamMessageTextFontPathTheirs="fonts/LilyoftheValley.ttf"
	app:streamReadStateTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamAvatarTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamAttachmentDescriptionTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamAttachmentFileSizeTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamAttachmentTitleTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamDateSeparatorDateTextFontPath="fonts/LilyoftheValley.ttf"
	...
 />
```

image

## MessageInputView
```xml
<com.getstream.sdk.chat.view.MessageInputView
	...
	app:streamInputTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamAvatarTextFontPath="fonts/LilyoftheValley.ttf"
	app:streamInputBackgroundTextFontPath="fonts/LilyoftheValley.ttf"
	...
/>
```

image

### CODE REVIEW

**Comment by elevenetc** [comment]
@adrian09h there is also a requirement to replace fonts for the whole library, which actually makes sense. The first thing which comes into my mind is make our own `TextView` and through some static reference with `StreamChat` set global font. But there're should be also available per `TextView` overriding.

**Comment by adrian09h** [comment]
> @adrian09h there is also a requirement to replace fonts for the whole library (see excel 52 issue), which actually makes sense. The first thing which comes into my mind is make our own `TextView` and through some static reference with `StreamChat` set global font. But there're should be also available per `TextView` overriding.

Yeah, Exactly, I thought global custom font about whole library, either. so I was going to add custom font param in `StreamChat`.
Maybe it might be easier to developer about whole custom font or per textView?

- Setter
```
StreamChat.setFontPath("fonts/LilyoftheValley.ttf");
```

-  use case
```
public static void setCustomTextFont(TextView textView, String fontPath, int textStyle, Context context){

	String fontPath_ = TextUtils.isEmpty(StreamChat.getFontPath())? fontPath : StreamChat.getFontPath();

	if (!TextUtils.isEmpty(fontPath_)){
		try {
			Typeface font = Typeface.createFromAsset(context.getAssets(), fontPath_);
			textView.setTypeface(font);
		}catch (RuntimeException e){
			e.printStackTrace();
		}
	}else
		textView.setTypeface(Typeface.DEFAULT, textStyle);
}
```

**Comment by elevenetc** [comment]
Yes, I also was thinking about defining it in `StreamChat`.
It needed to be a bit more complicated thought:
1. We need to keep fonts in memory, but not load them every time, load from assets is expensive.
2. Also there're two basic ways of loading fonts: from asset directory and from resources directory. We need to support both. 
3. We have lots of repeated code with font, colors, style and size settings.

So I introduced
- `FontsManager` which keeps fonts in memory and takes all fonts related work
- `TextStyle` which basically saves some repeated lines, makes safer definition (forces us to define both types of fonts for example)
- `StreamChatStyle` which has global styles.

**Comment by adrian09h** [comment]
@elevenetc Really looks great.

**Pull request merged**
