### PR TITLE
Update tint of thread replies ornaments

### PR DESCRIPTION
**Pull request by samiuelson**
https://stream-io.atlassian.net/browse/CAS-510
### Description

Update of "ornament" tint to match bubble background.
Screenshot 2021-01-07 at 10 34 13
Screenshot 2021-01-07 at 10 33 58

### Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
~- [ ] Changelog updated with client-facing changes~
~- [ ] New code is covered by unit tests~
- [x] Comparison screenshots added for visual changes
- [x] Reviewers added

### CODE REVIEW

**Comment by leandroBorgesFerreira** [comment]
I think this part gets tinted... Let me check

**Review by leandroBorgesFerreira — DISMISSED** [review]
I believe this is not changing the colour. This is where you should do it:

```
<androidx.appcompat.widget.AppCompatImageView
        android:id="@+id/threadsOrnamentLeft"
        android:layout_width="13dp"
        android:layout_height="33dp"
        android:src="@drawable/stream_ui_thread_replies_ornament_left"
        app:tint="@color/stream_ui_thread_reply_stroke"
        />
```

I think we should use the colour black in the drawables and then we set the tint the way we prefer. But if you prefer to do in the XML of the drawable, delete the tint line and then it will be fine.

**Comment by zsmb13** [comment]
Agreed with the comment above, black + tinting should be preferred. Checking the screenshots in the PR description, I believe the ornaments are the same colour on both too.

**Comment by bychkovdmitry** [comment]
We need to review all the icons as there are lots of icons with tint applied directly in corresponding drawables

**Review by zsmb13 — APPROVED** [review]
LGTM

**Pull request merged**
