### PR TITLE
Update delete message background

### PR DESCRIPTION
**Pull request by JcMinarro**
### Description

Deleted messages have the same background color of normal messages. Only the text color changes (from black to grey).

| Before | After |
| --- | --- |
|  photo_2021-01-08_17-36-01 |  photo_2021-01-08_17-36-04  |

### Checklist
- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- ~[ ] Changelog updated with client-facing changes~
- ~[ ] New code is covered by unit tests~
- [x] Comparison screenshots added for visual changes
- [x] Reviewers added

### CODE REVIEW

**Comment by bychkovdmitry** [comment]
Screenshot 2021-01-08 at 20 08 18
Isn't the color #DBDBDB?

**Comment by bychkovdmitry** [comment]
Screenshot 2021-01-08 at 20 19 03
There is a 50% opacity here

**Comment by JcMinarro** [comment]
> Screenshot 2021-01-08 at 20 19 03
> 
> There is a 50% opacity here

It was required by designer :man_facepalming: 
Let me check with them

**Comment by JcMinarro** [comment]
@bychkovdmitry Designer already updated this color

**Review by bychkovdmitry — APPROVED** [review]

**Pull request merged**
