### PR TITLE
Feature/ease of use

### LINKED ISSUE #67: channel.query vs channel.watch
The JS library uses channel.query and channel.watch. The android lib only exposes channel.query with the behaviour of channel.watch. This is super confusing

### PR DESCRIPTION
**Pull request by tbarbugli**
# Submit a pull request

- Fixes #67 
- Hide client.getChannelByCID behind `client.channel`
- Add channel initialized state
- Channel View Model can be used to open a channel directly (ie. from a notification)
- Let device client's methods wait for `setUser`

### CODE REVIEW

**Comment by tschellenbach** [comment]
this is not backwards compatible right?

**Comment by tbarbugli** [comment]
> this is not backwards compatible right?

@tschellenbach it's not

- `client.getChannelByCid ` is now private (superseded by client.channel in a much simpler way)

- `channel.query` when used directly does not do `watch:true` anymore (only affects people using it directly, model views are not affected)

**Comment by tschellenbach** [comment]
ok, good to mention that in the release. also, do we need to change some calls from channel.query into channel.watch to make sure things still work?

**Comment by tbarbugli** [comment]
> ok, good to mention that in the release. also, do we need to change some calls from channel.query into channel.watch to make sure things still work?

yes I did that already in the ChannelViewModel, going to mention breaking changes in the Changelog

**Pull request merged**
