### PR TITLE
WIP [Compose] - 2547 - Add push notifications to sample app

### PR DESCRIPTION
**Pull request by bychkovdmitry**
https://github.com/GetStream/stream-chat-android/issues/2547

### 🎯 Goal

Add support for push notifications to the Compose sample app.

### ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Comparison screenshots added for visual changes
- [ ] Affected documentation updated (docusaurus, tutorial, CMS (task created))
- [x] Reviewers added

### CODE REVIEW

**Review by filbabic — APPROVED** [review]
Seems good to me, couldn't really find anyhting that doesn't work or looks out of place!

**Comment by bychkovdmitry** [comment]
This PR is blocked as it lacks Huawei API key and `agconnect-services.json`.

**Review by skydoves — APPROVED** [review]
Looks good to me!!
It's very amazing that we can implement the push notification things super easily. 😄

**Comment by bychkovdmitry** [comment]
Going to merge this without Huawei support and create a ticket for it.

**Pull request merged**
